baseURL = 'http://localhost:1313/'
languageCode = 'tr-tr'
title = 'OtoBlog'
theme = 'ananke'

[params]
  description = "Hugo ile yazılmış statik blog"
  author = "OtoBlog Yazarı"
  
[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Yazılar"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    identifier = "about"
    name = "Hakkında"
    url = "/about/"
    weight = 2 