apiVersion: apps/v1
kind: Deployment
metadata:
  name: otoblog
  labels:
    app: otoblog
spec:
  replicas: 2
  selector:
    matchLabels:
      app: otoblog
  template:
    metadata:
      labels:
        app: otoblog
    spec:
      containers:
      - name: otoblog
        image: otoblog:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5 