apiVersion: v1
kind: Service
metadata:
  name: otoblog
  labels:
    app: otoblog
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
    protocol: TCP
  selector:
    app: otoblog 